# Generated by Django 3.1.2 on 2020-10-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20201022_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='date_of_birth',
            field=models.DateTimeField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
